version: "3.7"
services:
  database:
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: database
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8010:8010"
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8020:8020"   
volumes:
  data: